version: 2

sphinx:
   configuration: docs/conf.py

build:
   os: ubuntu-24.04
   tools:
      python: "3.13"
   apt_packages:
      - tree      
   jobs:
      pre_create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
      create_environment:
         - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
      install:
         - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs
      post_build:
         # for debugging
         - tree .
         - head -n 30 docs/README.md