# workflow based on uv tutorial: https://docs.astral.sh/uv/guides/integration/github/#publishing-to-pypi

name: "Publish"

on:
  push:
    tags:
      # publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # pin specific uv version
          version: "0.8.15"        
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          # use latest python version compatible with project
          python-version-file: "pyproject.toml"
      - name: Build
        run: uv build
      #basic checks
      - name: LSteinCanvas test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/import_test.py
      - name: LSteinCanvas test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/import_test.py
      #publish to pypi
      - name: Publish
        run: uv publish